apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "storage.deployment.name" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: 
{{- include "storage.deployment.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "storage.deployment.selector" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "storage.container.name" . }}
        image: {{ .Values.pod.image }}
        args: {{ .Values.pod.args }}
        {{- include "storage.volumeMounts" . | indent 8 }}
        resources:
            requests:
              memory: {{ .Values.deployment.memory_request }}
              cpu: {{ .Values.deployment.cpu_request }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.DB_PASSWORD }}
        - name: MYSQL_DATABASE
          value: {{ .Values.DB_NAME }}
      {{- include "storage.volumes" . | indent 6 }}
