apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector: 
{{- include "storage.deployment.selector" . | indent 4 }}
{{- include "storage.service.ports" . | indent 2 }}
  type: {{ .Values.service.type }}