apiVersion: apps/v1
kind: Deployment
metadata:
{{- include "api_gateway.deployment.name" . | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:  
{{- include "api_gateway.deployment.selector" . | indent 6 }}
  template:
    metadata:
      annotations:
{{- toYaml .Values.scrapeConfig | nindent 8 }}
      labels:
{{- include "api_gateway.deployment.selector" . | indent 8 }}
    spec:
      containers:
        - name: {{ template "api_gateway.deployment.containerName" . }}
          image: {{ .Values.imageName | default "trivedhaudurthi/qna_apigateway:v1" }}
          imagePullPolicy: {{ .Values.api_gateway.deployment.imagePullPolicy }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.DB_PASSWORD }}
          resources:
            requests:
              memory: {{ .Values.api_gateway.deployment.memory_request }}
              cpu: {{ .Values.api_gateway.deployment.cpu_request }}
          ports:
            - name: {{ .Values.api_gateway.deployment.port_name }}
              containerPort: {{ .Values.api_gateway.deployment.container_port }}
              hostPort: {{ .Values.api_gateway.deployment.container_port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api_gateway.deployment.liveness_path }}
              port: {{ .Values.api_gateway.deployment.port_name }}
            failureThreshold: {{ .Values.api_gateway.deployment.liveness_failure_threshold }}
            periodSeconds: {{ .Values.api_gateway.deployment.liveness_period_seconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.api_gateway.deployment.liveness_path }}
              port: {{ .Values.api_gateway.deployment.port_name }}
            failureThreshold: {{ .Values.api_gateway.deployment.startup_failure_threshold }}
            periodSeconds: {{ .Values.api_gateway.deployment.startup_period_seconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api_gateway.deployment.liveness_path }}
              port: {{ .Values.api_gateway.deployment.port_name }}
            periodSeconds: {{ .Values.api_gateway.deployment.readiness_period_seconds }}
          
