apiVersion: v1
kind: Service
metadata:
{{- include "api_gateway.service.name" . | indent 2}}
spec:
  selector:
{{- include "api_gateway.service.selector" . | indent 4 }}
{{- include "api_gateway.service.ports" . | indent 2 }}
  type: {{ .Values.api_gateway.service.type }}