# Default values for qna_apigateway_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api_gateway:
  deployment:
    name: qna-apigateway-deployment
    selectorLabel:
      app: qna-apigateway-pod
    replicas: 1
    imagePullPolicy: IfNotPresent
    podName: qna-apigateway-pod
    containerName: qna-apigateway-container
    memory_request: "400Mi"
    cpu_request: "400m"
    container_port: 8080
    port_name: liveness-port
    liveness_path: /v1/question
    liveness_failure_threshold: 2
    liveness_period_seconds: 10
    startup_failure_threshold: 30
    startup_period_seconds: 10
    readiness_period_seconds: 20
  service:
    name: qna-apigateway-service
    labels: 
      service: qna-api-gateway-service
    selectorLabel:
      app: qna-apigateway-pod
    ports:
    - port: 8080
      name: http
    type: ClusterIP
  hpa:
    targetCPUUtilizationPercentage: 50
scrapeConfig:
  prometheus.io/scrape: 'true'
  prometheus.io/path: '/actuator/prometheus'
  prometheus.io/port: 8080

