name: Deploy api_gateway microservice
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_docker_image:
    name: Build and push docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: trivedhaudurthi/qna_apigateway:v${{ github.run_number }}
  deploy_chart_to_cluster:
    name: Deploy helm chart to cluster
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt install -y curl
          sudo apt-get install -y unzip 
      - name: Install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Install Kubectl and helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
      - name: Configure Kubectl
        run: |
          aws eks update-kubeconfig --name qna_cluster
      - name: Install helm charts
        uses: actions/checkout@v2
        run: |
            ./deploy_mysql_chart.sh
            ./deploy_api_gateway_chart.sh
        env:
          imageName: trivedhaudurthi/qna_apigateway:v${{ github.run_number }}
          dbPassword: ${{ secrets.DB_PASSWORD }}
        


