name: Deploy api_gateway microservice
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_docker_image:
    name: Build and push docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "trivedhaudurthi/qna_apigateway:$GITHUB_RUN_NUMBER"